version: '3.9'

services:
    api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - '5257:5257'
        volumes:
            - ~/.vsdbg:/remote_debugger:rw
